@startuml add-exco-to-cca

skinparam defaultFontSize 12
skinparam SequenceArrowThickness 1.2
skinparam SequenceParticipantBackgroundColor #f9f9f9
skinparam maxMessageSize 300

title Add EXCO to CCA

actor ":User" as User
participant "ccaLedger" as CL
participant "ui" as Ui
participant "parser" as Parser
participant "cmd : AddExcoCmd" as Command

box "Logic Layer" #f2f2f2
    participant "Managers" as MGR
end box

ref over User, CL, Ui, Parser, Command : SD_CommandExecution

' Data Retrieval
Command -> MGR : getCCAList()
activate MGR
MGR --> Command : ccaList
deactivate MGR

Command -> MGR : getResidentList()
activate MGR
MGR --> Command : residentList
deactivate MGR

' Logic Flow
alt CCA / Resident not found
    Command -> Ui : showError("Not found")
else Resident already in CCA
    Command -> Ui : showError("Already in CCA")
else Success
    ' Showing internal logic as a combined action to save horizontal space
    Command -> Command : updateDomainModels(res, cca)
    activate Command
    deactivate Command

    Command -> Ui : showMessage("Added as EXCO...")
    activate Ui
    Ui --> Command
    deactivate Ui
end

Command --> CL
deactivate Command

@enduml