@startuml view-exco

skinparam defaultFontSize 13
skinparam SequenceArrowThickness 1.5
skinparam SequenceParticipantBackgroundColor #f9f9f9

title view-exco Command

actor ":User" as User
participant "ccaLedger : CcaLedger" as CcaLedger
participant "ui : Ui" as Ui
participant "parser : Parser" as Parser
participant "command : ViewCcaExco" as Command
participant "ccaManager : CcaManager" as CcaManager

ref over User, CcaLedger, Ui, Parser, Command
  SD_CommandExecution
end ref

Command -> CcaManager : getCCAList()
activate CcaManager
CcaManager --> Command : ccaList : ArrayList<Cca>
deactivate CcaManager

alt CCA not found
    Command -> Ui : showError("CCA not found")
    activate Ui
    Ui --> Command
    deactivate Ui
else CCA found
    Command -> Command : cca.getExcos()
    Command -> Ui : showExcoList(excoList)
    activate Ui
    Ui --> Command
    deactivate Ui
end

Command --> CcaLedger
deactivate Command

@enduml